stages:
  - build

before_script:
  - docker info

latest:
  image: docker:latest
  tags:
   - docker-gcc
  stage: build
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "tcp://localhost:2375/"]
      command: ["dockerd-entrypoint.sh"]
  script: |
    echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    c="precheck"
    echo "Building container: $c:latest"
    docker build --no-cache -t registry.gitlab.com/gacybercenter/open/precheck/$c:latest $c/.
    echo "Deploying Container Image: $c:latest"
    docker push registry.gitlab.com/gacybercenter/open/precheck/$c:latest


build:
  image: docker:latest
  tags:
   - docker-gcc
  stage: build
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "tcp://localhost:2375/"]
      command: ["dockerd-entrypoint.sh"]
  script: |
    echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    c="precheck"
    echo "Building container: $c:${CI_COMMIT_SHORT_SHA}"
    docker build --no-cache -t registry.gitlab.com/gacybercenter/open/precheck/$c:${CI_COMMIT_SHORT_SHA} $c/.
    echo "Deploying Container Image: $c:${CI_COMMIT_SHORT_SHA}"
    docker push registry.gitlab.com/gacybercenter/open/precheck/$c:${CI_COMMIT_SHORT_SHA}

