version: '3'
services:
  node:
    image: precheck:latest
    container_name: precheck
    restart: always
    environment:
      - TITLE=Georgia Cyber Range Precheck
    volumes:
      - /var/www/html:/var/www/html
    ports:
      - 80:80
    networks:
      - precheck-net

  websocket-node:
    image: jmalloc/echo-server:latest
    container_name: websocket
    restart: always
    ports:
      - 8080:8080
    networks:
      - precheck-net

networks:
  precheck-net: